### ISSUE TITLE
CTD when entering the End

### ISSUE THREAD

**Issue by niallator11** [Amaxter/Ultra-Modded-Survival#1]
Upon entering the End portal my game crashed to the desktop, i haven't been able to load the save up since.

Crash Report: http://pastebin.com/WE0VtPTr

**Comment by Amaxter** [comment]
Do you have a  backup of your world you can restore from? I;m going to see if I can reproduce your issue.

**Comment by Amaxter** [comment]
Aha, I have reproduced it, fix incoming.

**Comment by niallator11** [comment]
Ok, sorry was in progress of trying to post the file but couldn't, I haven't used github before so i wasn't sure what to do, thank you anyway, enjoying the mod pack a lot

**Comment by Amaxter** [comment]
Try removing Chocolate Quest for now. I have submitted the error to the mod author.

**Comment by Amaxter** [comment]
Fixed in latest update, temporarily removed Chocolate Quest until this issue is fixed.

**Comment by Onetimetwotimes** [comment]
You can fix the crash with chocolate quest included by disabling test caves in the config file at: Ultra Modded Survival/config/chocolate/dungeonconfig/caveTests.prop

Change chance to 0, then put chocolate quest back into the mods folder.

**Comment by Amaxter** [comment]
It works, thank you! Will reinclude Chocolate Quest for the next update.
