### ISSUE TITLE
Ultra Modded Survival failure to download

### ISSUE THREAD

**Issue by Corley571** [Amaxter/Ultra-Modded-Survival#12]
I have an issue when attempting to download Ultra modded survival. When I press the install button, the pack checks for local files then begins to download never mine, and stops downloading, with only delete pack and install buttons, no play button. I tried deleting the pack and it downloads everything until it gets to never mine, and stops. The most recent log can be found here: http://pastebin.com/a9yZqHDj

**Comment by Amaxter** [comment]
Is your internet very slow? Try deleting and reinstalling again. Not a pack issue, seems to be a problem on your end (likely your internet) so I am closing this. Good luck.
