### ISSUE TITLE
Loading problem

### ISSUE THREAD

**Issue by UnsuitableSnow** [Amaxter/Ultra-Modded-Survival#13]
the pack stops loading at 57% Ars Magica 2 everytime. what should i do?

**Comment by Amaxter** [comment]
Allocate more RAM. Make sue you're using Java 8 64 bit. It's odd because the launcher should stop silly people like you from launching the pack without enough memory. Send me your logs.

**Comment by UnsuitableSnow** [comment]
I do have 8 gbs set I deleted ars magica 2 from the pack and it runs smoothly but I would like to put it back any ideas? I'm probably sounding like an annoying person ( very sorry but would like to figure it out :/   )

**Comment by Amaxter** [comment]
Download server field, extract it from there, insert in the pack directory/mods. Or reinstall the pack via the launcher in Modpack Options (this will delete your worlds).
