### ISSUE TITLE
Own Server

### ISSUE THREAD

**Issue by ThePotatoTom** [Amaxter/Ultra-Modded-Survival#14]
So my friend has a server, and yesterday it was running fine, but now, we cannot seem to remove the mod OreSpawn. Every time he manually removes it installs it again. So sorry if this isnt really a modpack issue but I was wondering how to remove OreSpawn and Jerry's Tree for a server

**Comment by Amaxter** [comment]
If you're using a hosting company mention it to them, some who install modpacks automatically force that the mods stay the way they are. For Jerry's tree to not spawn delete the structures folder. Next time don't go to GitHub for an issue like this, that belongs in discussion. I'm closing this issue as it's irrelevant, good luck.
