### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by EvolDarwin** [Amaxter/Ultra-Modded-Survival#2]
My friend and I are trying to play on my server and every time he tries to load it. It says "This Modpack requires 2.5 GB RAM. You are using 1 GB RAM. You can use 2.5 GB" and "This modpack requires Java 1.8. You are using 1.7.0_79 64-Bit.". When he changes the Java it doesn't let him have the 2.5 GB of RAM. When he has the 2.5 GB of RAM he can't use the current Java. Please help!
![ac5697a5104c1f018bb9c72588bca10362d38d94381ab160de pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/13456096/8833653/c67056ec-3064-11e5-9884-cfa5ef9fdc31.jpg)

**Comment by Amaxter** [comment]
Make sure he selects that 64 bit version of Java in the launcher settings.

**Comment by EvolDarwin** [comment]
Thanks
