### ISSUE TITLE
Blizz/Basalz Bug

### ISSUE THREAD

**Issue by soda5261** [Amaxter/Ultra-Modded-Survival#3]
Blizzes and Basalz are invisble, at least to me. I'm not sure if it's my computer or the pack itself, but the DivineRPG ice dimension has invisible Blizzes and the Nether has invisible Basalz. Also, they are still invisible if you use a spawn egg in any dimension. They also don't show up when using damage indicators, waila, or any other mod. They still make noise, can be killed, can kill other things, and have normal drops.

**Comment by Amaxter** [comment]
Try removing OptiFine, then see if they're still invisible.

**Comment by soda5261** [comment]
I removed optifine, both are still invisble. Normal minecraft blazes are still visible, so its most likely a thermal foundation thing, possibly incompatible with a different mod.

**Comment by Amaxter** [comment]
Ok, I will look into the issue. Thanks for letting me know.

**Comment by soda5261** [comment]
You're welcome i guess

**Comment by soda5261** [comment]
Quick thing i just looked at: In the thermal foundation folder, it has the textures for the entities, so it did properly download the textures.

**Comment by Amaxter** [comment]
Yeah, talking to Team CoFH now.

**Comment by soda5261** [comment]
Also the blitz (Didnt know about it till i looked at the entity textures) is invisble

**Comment by soda5261** [comment]
Also they don't appear on my minimap

**Comment by Amaxter** [comment]
Ok, so it appears to be OreSpawn that's causing the issue (not a surprise, that mod is AWFUL :P), will talk to the devs of OreSpawn.

**Comment by Amaxter** [comment]
This issue is unsolvable I'm afraid, after some more research I discovered that the developer has abandoned the mod to work on his own game. Afraid this issue is unsolvable, so I'm closing it for now. Sorry.

**Comment by soda5261** [comment]
Amaxter i might, very big MIGHT, have possibly found a fix, at least for blitz.
![2015-07-23_12 56 30](https://cloud.githubusercontent.com/assets/13458952/8856745/a4ef8e3a-313a-11e5-85f6-8a11aab46d6c.png)

**Comment by Amaxter** [comment]
What did you do?

**Comment by soda5261** [comment]
I changed the config file for the entity id, im looking for the Basalz and Blizz still because it removes the spawn egg, if i find them i'll let you know

**Comment by Amaxter** [comment]
Ok, thank you :). Give me more info when you find it.

**Comment by soda5261** [comment]
![2015-07-23_13 08 51](https://cloud.githubusercontent.com/assets/13458952/8856943/1105f054-313c-11e5-80ee-6ba4decf6c77.png)
 Found the Blizz meaning the Basalz probably works too

**Comment by Amaxter** [comment]
Which mod did you change the Ids for? Thermal Foundation?

**Comment by soda5261** [comment]
Its in .technic/modpacks/ultra-modded-survival-101/config/cofh/thermalfoundation. Inside there is a file called "common". Scroll down to mobs and change it to what i have below and it should work fine as long as you change all 3 entities. If you want to test go to the DivineRPG ice dimension and look for blizzes.

# Set this to false for the Blizz to use a mod-specific ID; this removes the Spawn Egg.
        B:UseGlobalId=false

**Comment by soda5261** [comment]
Did it work?

**Comment by Amaxter** [comment]
It did, ok, will do for next update. Thanks for your help.

**Comment by AlphaMage22** [comment]
I'm having the same issue, but sadly I can not follow what you are saying about configing

**Comment by ethancook2** [comment]
Me too

**Comment by ethancook2** [comment]
But the weird thing is I saw a blizzard when I started the world and now there are basalzes right outside my house and I can't find them

**Comment by ethancook2** [comment]
Blizz**
