### ISSUE TITLE
UMS Server 1.2

### ISSUE THREAD

**Issue by ghost** [Amaxter/Ultra-Modded-Survival#35]
I had an older ums server and It worked perfectly until I updated this is my error:http://pastebin.com/27dKx3xG

**Comment by Amaxter** [comment]
Remove aroma backup

**Comment by ghost** [comment]
How did you fix that so fast

**Comment by ghost** [comment]
How do I do that?

**Comment by Amaxter** [comment]
It's in the mod's folder

**Comment by ghost** [comment]
Just remove that mod?

**Comment by ghost** [comment]
Why wasn't removed in the download

**Comment by ghost** [comment]
How about aroma core

**Comment by Amaxter** [comment]
That too :)

**Comment by ghost** [comment]
How did you fix the problem so fast?

**Comment by ghost** [comment]
Btw it worked
