### ISSUE TITLE
Technic Launcher UMS crashes during startup

### ISSUE THREAD

**Issue by atk0309** [Amaxter/Ultra-Modded-Survival#36]
Crash Report: http://pastebin.com/wi4wyhq2
Info: 4 GB memory allocated
Java - Latest version
Graphic drivers - Latest version
No modifications done whatsoever. 

Actions taken. 
1. Click install in the Technic Platform
2. Click play
3. Pre loading starts
4. Post loading starts - around 80-ish % it crashes and gets me back to the technic launcher. 

Regards,
atk

**Comment by YourturnGaming** [comment]
Use llibrary 0.3.3 instead of 0.4.3, make sure you delete the config file for it.

**Comment by atk0309** [comment]
Worked !
