### ISSUE TITLE
Crashed in log

### ISSUE THREAD

**Issue by HCHexY** [Amaxter/Ultra-Modded-Survival#4]
I´ve downloaded the modpack and when i hit play it crashes without making a crash report, here´s the crash section of the log: http://pastebin.com/0aG25kf4

**Comment by Amaxter** [comment]
Pleas provide the full log :)

**Comment by Amaxter** [comment]
I've verified this isn't an issue with the pack, launches fine for me and some other people I've tested with. Try two things:
1) Update your Java
2) Reinstall the pack
As this is a personal issue and not an issue with the pack I'm going to close this issue. Good luck!
