### ISSUE TITLE
Modpack Won't Start!

### ISSUE THREAD

**Issue by challenger1** [Amaxter/Ultra-Modded-Survival#6]
The modpack will install fine and then create the minecraft loading window. This gets to 85%,stops loading, and crashes. The crash report is on pastebin under the title "Amaxter Ultra-Modded-Survival Crash Report" at http://pastebin.com/zA1bLLY8. I can't wait to start playing this modpack and really appreciate the help!! Thanks!!

**Comment by Amaxter** [comment]
Please update your Java, this isn't an issue with the modpack so I'm closing this, good luck.
