### ISSUE TITLE
Constant Crashes when playing

### ISSUE THREAD

**Issue by niallator11** [Amaxter/Ultra-Modded-Survival#7]
Whilst playing i keep encountering constant crashes when playing for about 10 minutes, I'm unsure as to whether its just my save or a bug in one of the mods.
 
Crash Report: http://pastebin.com/MifKzQ5z

**Comment by Amaxter** [comment]
It's likely your save. Try another world or restore from an Aroma Backup that was working.

**Comment by Amaxter** [comment]
I haven't gotten this reported by anyone else, and in my personal testing it's fine. Closing until someone else confirms they're getting this often.

**Comment by whitepyros** [comment]
I have seen this bug before a lot, its an issue with optifine and your graphics card, if you remove optifine the crashes will stop
