### ISSUE TITLE
Horrible lag spikes.

### ISSUE THREAD

**Issue by VenomousBanana** [Amaxter/Ultra-Modded-Survival#8]
Hello, I have really been looking forward to playing this modpack but i can't seem to get rid of the constant lag spikes. For example, I will start up a world and my fps is at 60 - 70 fps, normal. After a few minutes in i start to drop down to about 5-10 fps, every 30 seconds or so and they last about 10 seconds. I have already updated my java to the most recent, updated my Nvidia drivers, and memory set to 5 Gb. I also don't believe it is a hardware problem either. Here are some of my specs:
CPU: Intel Core i7-4700MQ
GPU: GeForce GTX 765M
Ram: 32GB total, 16 GB usable

Any help would be greatly appreciated. Thank You

**Comment by Amaxter** [comment]
Make sure you are using the latest version of Java and have proper video card drivers. I haven't heard this from many others, so seems like an issue on your end. I wish you luck.
